Refactored to support RabbitMq.Client 7 and higher (#77)
* Refactored

* Fix for build

* Fix for build

* Fix for build

* fix for build

* Fix for build

* fix for build

* Fix for build

* Excluded sample project from solution

* Bumped version to 9.x

* Added custom tags for PRS

* Print temp version

* Fix for tag name

* Added tag on successful build

* Changed tag suffix name

* Fix for release

* Unified dotnet version

* Switched release notes to file

* Fix NUGET_KEY

* Changed workdir #major

* added tags cleanup

* Changed package Title

* Fix for publish

* Fix for deploy

* Reverted Package Name

* Updated Covertlet

* Reverted names

* Rename

* Fix UseSsl parameter (#78)

* fix: UseSsl parameter, adjust code comments, code format.

* chore: Use https in links.

* fix: UseSsl string comparison.

* chore: Simplify expression.

---------

Co-authored-by: rncwnd79 <>

---------

Co-authored-by: Mr. T. <28432599+rncwnd79@users.noreply.github.com>

diff --git a/.github/workflows/bump.yml b/.github/workflows/bump.yml
--- a/.github/workflows/bump.yml
+++ b/.github/workflows/bump.yml
@@ -1,42 +1,60 @@
 name: Bump version
 on:
+  push:
+    branches:
+      - master  # Run version bump when code is pushed to master
   pull_request:
     types:
-      - closed
-    branches:
-      - master
-jobs:
-  build:
-    name: Build check
-    runs-on: windows-2019
-    steps:
-      - uses: actions/checkout@v3
-      - name: Setup .NET Core
-        uses: actions/setup-dotnet@v3
-        with:
-          dotnet-version: 6.0.x
-      - name: Install dependencies
-        run: dotnet restore
-      - name: Build
-        run: dotnet build --configuration Release --no-restore
-      - name: Test
-        run: dotnet test --no-restore --verbosity normal
+      - closed  # Run PR tag cleanup when a PR is closed
 
-  bump:
-    name: Bump Version
-    needs: build
-    runs-on: ubuntu-22.04
+jobs:
+  version-bump:
+    if: github.event_name == 'push'
+    runs-on: ubuntu-latest
     permissions:
       contents: write
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Build Solution
+        uses: artdolya/actions/dotnet@master
         with:
-          ref: ${{ github.event.pull_request.head.sha }}
-          fetch-depth: '0'
-          
+          dotnet-version: ${{ vars.DOTNET_VERSION }}
+          run-tests: true
+
       - name: Bump version and push tag
         uses: anothrNick/github-tag-action@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           DEFAULT_BUMP: patch
           WITH_V: false
+          
+  delete-pr-tags:
+    if: github.event_name == 'pull_request'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0  # Ensures all tags are available
+  
+      - name: Configure Git
+        run: |
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+  
+      - name: Get PR Number
+        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
+  
+      - name: Find and Delete PR Tags
+        run: |
+          TAGS=$(git tag | grep "pr-${PR_NUMBER}." || true)
+          
+          if [ -n "$TAGS" ]; then
+            echo "Deleting tags: $TAGS"
+            git push --delete origin $TAGS
+          else
+            echo "No matching PR tags found."
+          fi
+
